"""engine/research/strategy_lifecycle.py — Strategy Lifecycle Manager
(SLM) Phase 0: state machine + transition rules + Pydantic audit-block
schemas.

Doctrine reference: 2026-05-31 deploy-platform RFC ("Strategy Lifecycle
Manager, NOT one-click deploy"). See conversation log + memory entry
[[feedback-promote-deploy-allocate-are-three-gates-2026-05-31]] (write
after Phase 0 ships).

This module provides:

  1. StrategyState enum — the 10 lifecycle states a deployed sleeve
     can be in, from PROPOSED through ARCHIVED.

  2. StateTransition — pure-data record of one transition,
     persisted by strategy_state_store.

  3. TransitionGate — the requirements (evidence) for each allowed
     (from_state, to_state) transition. Used by enforce_transition()
     to reject invalid moves at the type level.

  4. AuditBlocks (Pydantic v2) — typed schema that REPLACES manual
     YAML writing for cost_model + factor_exposure + capacity blocks.
     Validation is enforced at construction; downstream library_writer
     can emit YAML via .to_yaml() with guaranteed schema compliance.

Design principles:
  - Promote != Deploy. Three separate gates (PROMOTE / WIRE / ALLOCATE)
    map to (PROPOSED→AUDITED→APPROVED), (APPROVED→PAPER_TRADE), and
    (PAPER_TRADE→SHADOW→LIVE) respectively. Conflating violates least-
    privilege per the deploy-platform RFC.
  - Every transition records the actor (signature for audit trail).
  - Forward transitions are gated by evidence (Pydantic-validated).
  - Backward transitions (DECAY_WATCH → LIVE) are allowed but require
    explicit override flag — preventing accidental promotion-after-decay.

Pre-Phase-2 limitation: this module defines the gates but does NOT yet
enforce sequential-testing boundaries on PAPER_TRADE → SHADOW. Phase 2
adds the O'Brien-Fleming / Lan-DeMets alpha-spending check.
"""
from __future__ import annotations

import datetime as _dt
from enum import Enum
from pathlib import Path
from typing import Any, Literal, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
)


# ── 1. State enum ───────────────────────────────────────────────────────


class StrategyState(str, Enum):
    """The 10 lifecycle states a strategy can occupy.

    Terminal states: ARCHIVED, REJECTED (no outbound transitions).
    All other states are transient with allowed outbound moves defined
    in ALLOWED_TRANSITIONS.
    """

    PROPOSED = "PROPOSED"            # generated by hypothesis_generator
    AUDITED = "AUDITED"              # candidate_pipeline passed
    APPROVED = "APPROVED"            # human signoff recorded
    PAPER_TRADE = "PAPER_TRADE"      # forward observation, no real capital
    SHADOW = "SHADOW"                # tiny live capital (e.g. 1% AUM)
    LIVE = "LIVE"                    # full target allocation
    DECAY_WATCH = "DECAY_WATCH"      # decay sentinel SOFT alert active
    RAMP_DOWN = "RAMP_DOWN"          # decommissioning (decay HARD or manual)
    ARCHIVED = "ARCHIVED"            # terminal: decommissioned
    REJECTED = "REJECTED"            # terminal: failed audit / never deployed


class SleeveRole(str, Enum):
    """Per multi-role doctrine [[feedback-loop-refinement-multi-role-
    candidates-2026-05-30]] + FLAW 2/3 fixes (commit 2e0d499). Each role
    has DIFFERENT acceptance criteria — insurance is not measured on
    Sharpe; diversifier is not measured on alpha; regime_overlay is a
    meta-strategy on top of others.

    enforce_transition() consults ROLE_SPECIFIC_GATES[(role, from→to)]
    AFTER the base ALLOWED_TRANSITIONS gate passes, applying any extra
    role-conditional requirements (e.g. cosine ≤ -0.1 for diversifier).
    """

    ALPHA_SEEKER = "alpha_seeker"                 # D_PEAD, PIT SN — Sharpe + alpha t
    RISK_PREMIUM_HARVESTER = "risk_premium_harvester"   # carry, TSMOM — Sharpe vs HLZ
    INSURANCE = "insurance"                       # mom_hedge, crisis_hedge — hedge eff, NOT Sharpe
    REGIME_OVERLAY = "regime_overlay"             # vix_oas — switching attribution
    DIVERSIFIER = "diversifier"                   # TLT/GLD — cosine, NOT Sharpe

    @classmethod
    def from_yaml_value(cls, raw: str) -> "SleeveRole":
        """Parse the `factor_exposure.proposed_role` string from a library
        YAML into a SleeveRole. Wraps Enum() lookup with a clear error
        message that names the valid set, matching the strings accepted
        by library_factor_exposure_audit.VALID_ROLES and the
        candidate_pipeline `--proposed-role` CLI choices."""
        try:
            return cls(raw)
        except ValueError as exc:
            raise ValueError(
                f"proposed_role={raw!r} is not a valid SleeveRole; "
                f"accepted: {[r.value for r in cls]}"
            ) from exc


# ── Cross-module alignment guard ────────────────────────────────────────
# Single source of truth for the role-string set. If this set diverges
# from library_factor_exposure_audit.VALID_ROLES OR candidate_pipeline
# CLI choices, the assertion in tests/test_strategy_lifecycle.py will
# fail loudly. Do NOT edit one side without updating the others.
EXPECTED_ROLE_STRINGS_FROZEN: frozenset[str] = frozenset({
    "alpha_seeker", "risk_premium_harvester",
    "insurance", "regime_overlay", "diversifier",
})


# ── 2. Transition data records ──────────────────────────────────────────


class TransitionGate(BaseModel):
    """Evidence requirements for a single (from, to) transition.

    A gate is a *necessary* (not sufficient) condition. Domain-specific
    callers may impose additional checks beyond what's captured here.
    """

    model_config = ConfigDict(frozen=True)

    requires_candidate_pipeline_run: bool = False
    requires_human_approval: bool = False
    requires_min_paper_trade_months: int = 0
    requires_sequential_test_pass: bool = False
    requires_ramp_protocol_step: Optional[int] = None
    requires_decay_alert_level: Optional[Literal["INFO", "SOFT", "HARD"]] = None
    requires_explicit_override: bool = False
    rationale: str = ""


# ── 3. Allowed transitions table ────────────────────────────────────────
#
# Inspired by:
#   - AQR Beacon strategy lifecycle (public talks 2018-2022)
#   - WorldQuant Alpha Pool auto-decommission framework
#   - Lopez de Prado, "Advances in Financial ML" Ch 10-11
#
# Backward / repair transitions (e.g. DECAY_WATCH → LIVE) intentionally
# require `allows_explicit_override=True` so callers must pass an
# override flag — prevents accidental re-promotion after decay alert.

ALLOWED_TRANSITIONS: dict[tuple[StrategyState, StrategyState], TransitionGate] = {
    # PROPOSED → AUDITED: candidate_pipeline must have run and produced verdict
    (StrategyState.PROPOSED, StrategyState.AUDITED): TransitionGate(
        requires_candidate_pipeline_run=True,
        rationale="candidate_pipeline.PipelineReport required to mark AUDITED",
    ),
    # PROPOSED → REJECTED: candidate_pipeline issued REJECT verdict
    (StrategyState.PROPOSED, StrategyState.REJECTED): TransitionGate(
        requires_candidate_pipeline_run=True,
        rationale="candidate_pipeline verdict REJECT moves to terminal REJECTED",
    ),
    # AUDITED → APPROVED: human signoff (PROMOTE gate)
    (StrategyState.AUDITED, StrategyState.APPROVED): TransitionGate(
        requires_human_approval=True,
        rationale="PROMOTE gate: human signoff required to elevate to APPROVED",
    ),
    # AUDITED → REJECTED: human rejects despite audit pass
    (StrategyState.AUDITED, StrategyState.REJECTED): TransitionGate(
        requires_human_approval=True,
        rationale="human discretion to reject audited strategy (e.g. policy reasons)",
    ),
    # APPROVED → PAPER_TRADE: WIRE gate (auto-deploy script wires sleeve)
    (StrategyState.APPROVED, StrategyState.PAPER_TRADE): TransitionGate(
        rationale="WIRE gate: sleeve registered + paper trade started, no real capital",
    ),
    # PAPER_TRADE → SHADOW: ALLOCATE gate stage 1 (Phase 2 adds seq-test check)
    (StrategyState.PAPER_TRADE, StrategyState.SHADOW): TransitionGate(
        requires_min_paper_trade_months=6,
        requires_sequential_test_pass=True,
        requires_ramp_protocol_step=1,
        rationale="ALLOCATE stage 1: 6mo paper + seq-test pass + ramp to ~1% AUM",
    ),
    # PAPER_TRADE → REJECTED: seq-test early-stop loss boundary hit
    (StrategyState.PAPER_TRADE, StrategyState.REJECTED): TransitionGate(
        requires_sequential_test_pass=False,
        rationale="Sequential testing early-stop loss boundary triggered",
    ),
    # SHADOW → LIVE: ALLOCATE gate stage 2 (ramp through tiers)
    (StrategyState.SHADOW, StrategyState.LIVE): TransitionGate(
        requires_ramp_protocol_step=4,
        rationale="ALLOCATE stage 2: ramped through 1%→5%→15%→target band",
    ),
    # SHADOW → REJECTED: shadow trade Sharpe failed gating
    (StrategyState.SHADOW, StrategyState.REJECTED): TransitionGate(
        rationale="Shadow-trade Sharpe below ramp-gate threshold",
    ),
    # LIVE → DECAY_WATCH: decay sentinel SOFT alert fired
    (StrategyState.LIVE, StrategyState.DECAY_WATCH): TransitionGate(
        requires_decay_alert_level="SOFT",
        rationale="Decay sentinel SOFT alert: trailing Sharpe drift detected",
    ),
    # DECAY_WATCH → LIVE: decay reversed (requires explicit override)
    (StrategyState.DECAY_WATCH, StrategyState.LIVE): TransitionGate(
        requires_explicit_override=True,
        rationale="Decay reversal — requires explicit override to prevent accidental re-promote",
    ),
    # DECAY_WATCH → RAMP_DOWN: HARD alert triggers decommissioning
    (StrategyState.DECAY_WATCH, StrategyState.RAMP_DOWN): TransitionGate(
        requires_decay_alert_level="HARD",
        rationale="Decay sentinel HARD alert: begin auto-decommissioning",
    ),
    # LIVE → RAMP_DOWN: manual decommission (e.g. policy change)
    (StrategyState.LIVE, StrategyState.RAMP_DOWN): TransitionGate(
        requires_human_approval=True,
        rationale="Manual decommission decision (policy / capacity / replacement)",
    ),
    # RAMP_DOWN → ARCHIVED: ramp completed (allocation reached 0)
    (StrategyState.RAMP_DOWN, StrategyState.ARCHIVED): TransitionGate(
        rationale="Ramp-down completed; allocation 0; strategy archived",
    ),
}


def is_terminal(state: StrategyState) -> bool:
    return state in {StrategyState.ARCHIVED, StrategyState.REJECTED}


def allowed_next_states(state: StrategyState) -> list[StrategyState]:
    """All states reachable from `state` in one transition."""
    return [to for (frm, to) in ALLOWED_TRANSITIONS if frm == state]


class InvalidTransitionError(ValueError):
    """Raised when caller attempts a transition not in ALLOWED_TRANSITIONS."""


class GateNotMetError(ValueError):
    """Raised when a transition is allowed in principle but its gate
    evidence is missing or fails validation."""


# ── 3b. Role-specific gates layer ───────────────────────────────────────
#
# Per multi-role doctrine: same (from_state, to_state) transition has
# DIFFERENT acceptance metrics depending on the sleeve's role. Examples:
#
#   alpha_seeker     PAPER_TRADE→SHADOW: trailing Sharpe ≥ P-D8 honest × 0.70
#   risk_premium     PAPER_TRADE→SHADOW: trailing Sharpe ≥ HLZ floor (0.50)
#   insurance        PAPER_TRADE→SHADOW: hedge ratio achieved (NOT Sharpe)
#   regime_overlay   PAPER_TRADE→SHADOW: switching attribution positive
#   diversifier      PAPER_TRADE→SHADOW: cosine ≤ -0.1 (NOT Sharpe)
#
# Phase 0 records the role-specific requirement *structurally*; the
# numerical thresholds are evaluated by Phase 2 sequential testing
# module. The base lifecycle accepts a `role_specific_evidence_passed`
# bool flag that the caller (Phase 2 framework) sets after evaluating
# the role-appropriate metric.


class RoleSpecificGate(BaseModel):
    """Extra requirements for a (role, from→to) tuple beyond the base
    TransitionGate. None means "no role-specific requirement at this
    transition for this role"."""

    model_config = ConfigDict(frozen=True)

    metric_name: str = Field(..., description="human-readable: 'trailing_sharpe', 'hedge_ratio', 'cosine_with_book'")
    threshold_description: str = Field(..., description="natural-language threshold; numeric eval is caller's job")
    rationale: str = ""


ROLE_SPECIFIC_GATES: dict[
    tuple[SleeveRole, StrategyState, StrategyState], RoleSpecificGate
] = {
    # ── alpha_seeker (D_PEAD, PIT SN) ─────────────────────────────────
    (SleeveRole.ALPHA_SEEKER, StrategyState.PAPER_TRADE, StrategyState.SHADOW):
        RoleSpecificGate(
            metric_name="trailing_sharpe",
            threshold_description="trailing 6mo Sharpe ≥ 0.70 × P-D8 honest target",
            rationale="alpha_seeker pays for itself via Sharpe; 70% of honest target is the conservative ramp-in bar",
        ),
    (SleeveRole.ALPHA_SEEKER, StrategyState.SHADOW, StrategyState.LIVE):
        RoleSpecificGate(
            metric_name="trailing_sharpe",
            threshold_description="trailing 12mo Sharpe ≥ 0.80 × P-D8 honest target",
            rationale="full LIVE requires near-target performance demonstrated post-ramp",
        ),
    (SleeveRole.ALPHA_SEEKER, StrategyState.LIVE, StrategyState.DECAY_WATCH):
        RoleSpecificGate(
            metric_name="trailing_sharpe",
            threshold_description="trailing 6mo Sharpe < 0.50 × honest target",
            rationale="alpha_seeker decay signal — Sharpe collapse",
        ),

    # ── risk_premium_harvester (carry, TSMOM) ─────────────────────────
    (SleeveRole.RISK_PREMIUM_HARVESTER, StrategyState.PAPER_TRADE, StrategyState.SHADOW):
        RoleSpecificGate(
            metric_name="trailing_sharpe",
            threshold_description="trailing 6mo Sharpe ≥ 0.50 (HLZ floor)",
            rationale="risk premium harvester — HLZ floor of 0.50 is conservative since the premium IS the alpha source",
        ),
    (SleeveRole.RISK_PREMIUM_HARVESTER, StrategyState.SHADOW, StrategyState.LIVE):
        RoleSpecificGate(
            metric_name="trailing_sharpe",
            threshold_description="trailing 12mo Sharpe ≥ 0.60",
            rationale="full LIVE for premium harvester at modest 0.60 bar",
        ),

    # ── insurance (mom_hedge, crisis_hedge) ───────────────────────────
    # NOTE: Sharpe is INTENTIONALLY NOT the metric. Insurance is bought
    # for negative-correlation hedge effectiveness, not return generation.
    (SleeveRole.INSURANCE, StrategyState.PAPER_TRADE, StrategyState.SHADOW):
        RoleSpecificGate(
            metric_name="hedge_correlation",
            threshold_description="hedge β with risk source ≤ -0.30 sustained over paper-trade window",
            rationale="insurance must demonstrate hedge effectiveness; weak Sharpe is BY DESIGN, not a failure mode",
        ),
    (SleeveRole.INSURANCE, StrategyState.SHADOW, StrategyState.LIVE):
        RoleSpecificGate(
            metric_name="crisis_period_pnl",
            threshold_description="positive PnL in any drawdown period >= 5% in source asset during shadow",
            rationale="insurance LIVE requires actual crisis-protection demonstration",
        ),
    (SleeveRole.INSURANCE, StrategyState.LIVE, StrategyState.DECAY_WATCH):
        RoleSpecificGate(
            metric_name="hedge_correlation",
            threshold_description="rolling 6mo hedge β with risk source > -0.10 (insurance not hedging anymore)",
            rationale="insurance decay = hedge breakdown, NOT Sharpe drop",
        ),

    # ── regime_overlay (vix_oas, multisig switching) ──────────────────
    (SleeveRole.REGIME_OVERLAY, StrategyState.PAPER_TRADE, StrategyState.SHADOW):
        RoleSpecificGate(
            metric_name="switching_attribution",
            threshold_description="positive Sharpe contribution from regime switching vs static baseline",
            rationale="regime overlay must demonstrate IT ADDED value vs holding static weights",
        ),
    (SleeveRole.REGIME_OVERLAY, StrategyState.SHADOW, StrategyState.LIVE):
        RoleSpecificGate(
            metric_name="regime_classifier_accuracy",
            threshold_description="regime classifier hit rate ≥ 60% in shadow",
            rationale="LIVE regime overlay requires classifier to be calibrated, not just lucky",
        ),

    # ── diversifier (TLT/GLD, low-cosine sleeves) ─────────────────────
    (SleeveRole.DIVERSIFIER, StrategyState.PAPER_TRADE, StrategyState.SHADOW):
        RoleSpecificGate(
            metric_name="cosine_with_book",
            threshold_description="cosine with deployed book ≤ -0.10 sustained over paper-trade window",
            rationale="diversifier is bought for negative cosine, NOT Sharpe — Sharpe can be 0 if cosine deeply negative",
        ),
    (SleeveRole.DIVERSIFIER, StrategyState.SHADOW, StrategyState.LIVE):
        RoleSpecificGate(
            metric_name="cosine_with_book",
            threshold_description="cosine remains ≤ -0.10 over shadow window",
            rationale="diversifier LIVE requires cosine to be STABLE — not just momentary",
        ),
    (SleeveRole.DIVERSIFIER, StrategyState.LIVE, StrategyState.DECAY_WATCH):
        RoleSpecificGate(
            metric_name="cosine_with_book",
            threshold_description="rolling 6mo cosine drifted > 0 (correlation flipped, no longer diversifying)",
            rationale="diversifier decay = cosine flip, NOT Sharpe",
        ),
}


def lookup_role_specific_gate(
    role: SleeveRole, from_state: StrategyState, to_state: StrategyState,
) -> Optional[RoleSpecificGate]:
    """Returns the role-specific gate for the given transition, or None
    if no extra requirement applies for this role at this transition."""
    return ROLE_SPECIFIC_GATES.get((role, from_state, to_state))


def enforce_transition(
    *,
    from_state: StrategyState,
    to_state: StrategyState,
    role: Optional[SleeveRole] = None,
    has_candidate_pipeline_run: bool = False,
    has_human_approval: bool = False,
    paper_trade_months: int = 0,
    sequential_test_pass: bool = False,
    role_specific_evidence_passed: bool = False,
    ramp_protocol_step: int = 0,
    decay_alert_level: Optional[Literal["INFO", "SOFT", "HARD"]] = None,
    explicit_override: bool = False,
) -> tuple[TransitionGate, Optional[RoleSpecificGate]]:
    """Validate a transition + its gate evidence. Returns
    (base_gate, role_specific_gate_or_None) on success;
    raises InvalidTransitionError or GateNotMetError on failure.

    Two-layer validation:
      1. Base gate (ALLOWED_TRANSITIONS) — structural eligibility
      2. Role-specific gate (ROLE_SPECIFIC_GATES) — role-conditional
         metric requirement; caller MUST evaluate the metric and pass
         role_specific_evidence_passed=True before this function will
         accept it.

    If role is None, role-specific layer is SKIPPED. Useful for system-
    initiated transitions (state-store internal moves) that shouldn't
    require role context.
    """
    key = (from_state, to_state)
    if key not in ALLOWED_TRANSITIONS:
        raise InvalidTransitionError(
            f"transition {from_state.value} → {to_state.value} is not allowed; "
            f"allowed next states from {from_state.value}: "
            f"{[s.value for s in allowed_next_states(from_state)]}"
        )
    gate = ALLOWED_TRANSITIONS[key]

    # For repair / backward transitions (DECAY_WATCH → LIVE etc.) the
    # gate REQUIRES an explicit override — preventing accidental re-
    # promotion. Override is checked FIRST so non-override callers
    # fail cleanly with a clear error.
    if gate.requires_explicit_override:
        if not explicit_override:
            raise GateNotMetError(
                f"{from_state.value} → {to_state.value} requires explicit_override=True "
                f"(reason: {gate.rationale})"
            )
        return gate, None

    if gate.requires_candidate_pipeline_run and not has_candidate_pipeline_run:
        raise GateNotMetError(
            f"{from_state.value} → {to_state.value} requires "
            f"candidate_pipeline run evidence"
        )
    if gate.requires_human_approval and not has_human_approval:
        raise GateNotMetError(
            f"{from_state.value} → {to_state.value} requires human approval signoff"
        )
    if paper_trade_months < gate.requires_min_paper_trade_months:
        raise GateNotMetError(
            f"{from_state.value} → {to_state.value} requires "
            f"≥{gate.requires_min_paper_trade_months} months paper trade "
            f"(have {paper_trade_months})"
        )
    if gate.requires_sequential_test_pass and not sequential_test_pass:
        raise GateNotMetError(
            f"{from_state.value} → {to_state.value} requires "
            f"sequential-test pass (O'Brien-Fleming / Lan-DeMets)"
        )
    if gate.requires_ramp_protocol_step is not None and \
            ramp_protocol_step < gate.requires_ramp_protocol_step:
        raise GateNotMetError(
            f"{from_state.value} → {to_state.value} requires ramp-protocol "
            f"step ≥{gate.requires_ramp_protocol_step} (have {ramp_protocol_step})"
        )
    if gate.requires_decay_alert_level is not None and \
            decay_alert_level != gate.requires_decay_alert_level:
        raise GateNotMetError(
            f"{from_state.value} → {to_state.value} requires decay alert level "
            f"={gate.requires_decay_alert_level} (have {decay_alert_level})"
        )

    # Role-specific layer: only evaluated if `role` provided
    role_gate: Optional[RoleSpecificGate] = None
    if role is not None:
        role_gate = lookup_role_specific_gate(role, from_state, to_state)
        if role_gate is not None and not role_specific_evidence_passed:
            raise GateNotMetError(
                f"{role.value} role-specific gate at {from_state.value} → "
                f"{to_state.value} NOT MET: metric={role_gate.metric_name}, "
                f"threshold={role_gate.threshold_description!r}"
            )
    return gate, role_gate


# ── 4. Persisted records ────────────────────────────────────────────────


class StateTransitionRecord(BaseModel):
    """Pure-data record persisted to state_transitions table on every
    successful enforce_transition() + state_store.transition() call."""

    model_config = ConfigDict(frozen=True)

    strategy_id: str = Field(..., min_length=1)
    from_state: Optional[StrategyState]
    to_state: StrategyState
    transition_at: _dt.datetime
    actor: str = Field(..., description="signer / script / system that triggered")
    reason: str = ""
    gate_evidence: dict[str, Any] = Field(default_factory=dict)
    git_sha: Optional[str] = None

    @field_validator("transition_at", mode="before")
    @classmethod
    def _coerce_dt(cls, v: Any) -> Any:
        if isinstance(v, str):
            return _dt.datetime.fromisoformat(v.replace("Z", "+00:00"))
        return v


# ── 5. Typed audit blocks (Pydantic v2) ─────────────────────────────────


class MultiAumSharpe(BaseModel):
    model_config = ConfigDict(frozen=True)
    at_10M: float
    at_100M: float
    at_1B: float


class CapacityBlock(BaseModel):
    model_config = ConfigDict(frozen=True)
    hard_capacity_usd: float = Field(..., gt=0)
    binding_constraint: str
    safe_deploy_band_usd: tuple[float, float]
    max_participation_assumed: float = Field(..., gt=0, lt=1)

    @model_validator(mode="after")
    def _validate_band(self) -> "CapacityBlock":
        lo, hi = self.safe_deploy_band_usd
        if lo >= hi:
            raise ValueError("safe_deploy_band_usd must be (lo, hi) with lo < hi")
        return self


class CostModelAudit(BaseModel):
    """Mirrors engine.research.library_cost_model_audit AUDITED_REQUIRED."""

    model_config = ConfigDict(frozen=True)

    audit_status: Literal["audited", "pending"]
    audit_priority: Optional[Literal["high", "medium", "low"]] = None
    audit_date: Optional[_dt.date] = None
    audit_script: Optional[str] = None
    audit_commit: Optional[str] = None
    type: Optional[Literal["almgren_chriss", "scalar_bps_buffer"]] = None
    half_spread_bps: Optional[float] = None
    impact_coef: Optional[float] = None
    daily_sigma_estimate: Optional[float] = None
    universe_median_adv_usd: Optional[float] = None
    n_positions_typical: Optional[int] = None
    monthly_turnover_estimate: Optional[float] = None
    stress_multiplier: Optional[float] = None
    rationale: Optional[str] = None
    multi_aum_sharpe_sleeve: Optional[MultiAumSharpe] = None
    capacity: Optional[CapacityBlock] = None
    caveats: Optional[str] = None

    @model_validator(mode="after")
    def _validate_completeness(self) -> "CostModelAudit":
        if self.audit_status == "audited":
            required = (
                "audit_date", "audit_script", "audit_commit", "type",
                "half_spread_bps", "impact_coef", "daily_sigma_estimate",
                "universe_median_adv_usd", "monthly_turnover_estimate",
                "stress_multiplier", "rationale",
                "multi_aum_sharpe_sleeve", "capacity",
            )
            missing = [k for k in required if getattr(self, k) is None]
            if missing:
                raise ValueError(
                    f"cost_model.audit_status=audited but missing: {missing}"
                )
            if self.rationale and len(self.rationale) < 50:
                raise ValueError("cost_model.rationale must be ≥ 50 chars when audited")
        elif self.audit_status == "pending" and self.audit_priority is None:
            raise ValueError("cost_model.audit_status=pending requires audit_priority")
        return self


class FactorExposureAudit(BaseModel):
    """Mirrors engine.research.library_factor_exposure_audit AUDITED_REQUIRED."""

    model_config = ConfigDict(frozen=True)

    audit_status: Literal["audited", "pending"]
    audit_priority: Optional[Literal["high", "medium", "low"]] = None
    audit_date: Optional[_dt.date] = None
    audit_script: Optional[str] = None
    audit_commit: Optional[str] = None
    phase: Optional[Literal[1, 2, 3, 4, 5]] = None
    proposed_role: Optional[Literal[
        "alpha_seeker", "risk_premium_harvester", "insurance",
        "regime_overlay", "diversifier",
    ]] = None
    n_months: Optional[int] = None
    alpha_annualized: Optional[float] = None
    alpha_t_hac: Optional[float] = None
    betas: Optional[dict[str, float]] = None
    t_stats_hac: Optional[dict[str, float]] = None
    r_squared: Optional[float] = None
    verdict: Optional[str] = None
    audit_blocks_deploy_decision: bool = False  # soft-gate doctrine
    factor_tilted_by_design: bool = False
    caveats: Optional[str] = None

    @model_validator(mode="after")
    def _validate_completeness(self) -> "FactorExposureAudit":
        if self.audit_status == "audited":
            required = (
                "audit_date", "audit_script", "audit_commit", "phase",
                "proposed_role", "n_months", "alpha_annualized",
                "alpha_t_hac", "betas", "t_stats_hac", "r_squared", "verdict",
            )
            missing = [k for k in required if getattr(self, k) is None]
            if missing:
                raise ValueError(
                    f"factor_exposure.audit_status=audited but missing: {missing}"
                )
            # Phase-1 minimum factor coverage
            if self.betas is not None:
                p1 = {"MKT", "SMB", "MOM"}
                if not p1.issubset(self.betas.keys()):
                    raise ValueError(
                        f"factor_exposure.betas must include {p1} (Phase-1 minimum); "
                        f"got {set(self.betas.keys())}"
                    )
        return self


class AuditBlocks(BaseModel):
    """Composite of cost_model + factor_exposure for a single strategy.

    Capacity is nested inside cost_model.capacity (matches existing
    library YAML schema). Future blocks (cross-asset risk model,
    L4 provenance, etc.) plug in here.
    """

    model_config = ConfigDict(frozen=True)

    cost_model: CostModelAudit
    factor_exposure: FactorExposureAudit


# ── 6. Strategy record (the row in strategy_state table) ────────────────


class StrategyRecord(BaseModel):
    """Aggregate state for one strategy. Mirrors strategy_state DB row.

    Forward-only fields (proposed_at, audited_at, …) are populated on
    state transitions; backward transitions do NOT clear them so the
    history of "first reached X" is preserved.
    """

    model_config = ConfigDict()

    strategy_id: str = Field(..., min_length=1)
    current_state: StrategyState
    proposed_at: Optional[_dt.datetime] = None
    audited_at: Optional[_dt.datetime] = None
    approved_at: Optional[_dt.datetime] = None
    approved_by: Optional[str] = None
    paper_trade_started: Optional[_dt.datetime] = None
    shadow_started: Optional[_dt.datetime] = None
    live_started: Optional[_dt.datetime] = None
    decommissioned_at: Optional[_dt.datetime] = None
    current_allocation_pct: float = 0.0
    target_allocation_pct: float = 0.0
    library_yaml_path: Optional[str] = None
    candidate_pipeline_run_id: Optional[str] = None
    parent_strategy_id: Optional[str] = None
    notes: str = ""
    created_at: _dt.datetime
    updated_at: _dt.datetime

    @field_validator("current_allocation_pct", "target_allocation_pct")
    @classmethod
    def _validate_alloc(cls, v: float) -> float:
        if v < 0 or v > 1.0:
            raise ValueError("allocation_pct must be in [0, 1]")
        return v
